version: "3"
services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    ports:
    - "1883:1883"
    - "9001:9001"
  unifi-scraper:
    container_name: unifi-scraper
    build:
      dockerfile: Dockerfile
      context: GlowingSquare_Unifi/web/
    restart: always
    ports:
    - "8080:80"